cspc_lidar:
  ros__parameters:
    port: /dev/sc_mini
    frame_id: laser_frame
    time_offset: -0.10
    ignore_array: ""
    baudrate: 57600
    samp_rate: 9
    resolution_fixed: true
    singleChannel: false
    auto_reconnect: true
    reversion: true
    isToFLidar: false
    angle_max: 180.0
    angle_min: -180.0
    max_range: 16.0
    min_range: 0.01
    frequency: 10.0
    version: 4
